name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  TEST_EXECUTION_ENV: qa
  SAUCE_DEMO_URL: "https://www.saucedemo.com"
  SAUCE_DEMO_TAB_NAME: "Swag Labs"
  DEMO_QA_URL: "https://demoqa.com"
  JQUERY_URL: "https://jqueryui.com"
  JQUERY_TAB_NAME: "jQuery UI"
  THE_INTERNET_URL_HEROKUAPP: "https://the-internet.herokuapp.com"
  PASSWORD: "secret_sauce"
  STANDARD_USER: "standard_user"
  INVALID_USER: "invalid_user"
  LOCKED_OUT_USER: "locked_out_user"
  PROBLEM_USER: "problem_user"
  PERFORMANCE_GLITCH_USER: "performance_glitch_user"
  ERROR_USER: "error_user"
  VISUAL_USER: "visual_user"
  USER_FIRST_NAME: "RandomFN"
  USER_LAST_NAME: "RandomLN"
  ZIP_CODE: "12345"
    
jobs:
  test-on-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and update snapshots
        run: npx playwright test --update-snapshots        
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-mac
          path: playwright-report/
          retention-days: 30

      - name: Upload updated snapshots
        uses: actions/upload-artifact@v4
        with:
          name: updated-snapshots-mac
          path: tests/TestingWithScreenshots/ValidateScreenshot.spec.ts-snapshots/
          
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failures-mac
          path: test-results/
          retention-days: 7

  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and update snapshots
        run: npx playwright test --update-snapshots        
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-linux
          path: playwright-report/
          retention-days: 30
        
      - name: Upload updated snapshots
        uses: actions/upload-artifact@v4
        with:
          name: updated-snapshots-linux
          path: tests/TestingWithScreenshots/ValidateScreenshot.spec.ts-snapshots/
            
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failures-linux
          path: test-results/
          retention-days: 7